Update env-cicd.yml

diff --git a/.github/workflows/env-cicd.yml b/.github/workflows/env-cicd.yml
--- a/.github/workflows/env-cicd.yml
+++ b/.github/workflows/env-cicd.yml
@@ -28,15 +28,35 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Generate & Copy .env 
-      uses: appleboy/scp-action@v0.1.7
+    - name: Fetch env_account file as base64
+      id: fetch-env
+      uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.PRODSM101_HOST }}
         username: ${{ secrets.PRODSM101_USERNAME }}
         key: ${{ secrets.PRODSM101_PRIVATE_KEY }}
         port: ${{ secrets.PRODSM101_PORT_SSH }}
-        source: "/opt/artitact-prod-m101/Store/env_account/*"
-        target: "./*"
+        script: |
+            cat /opt/artitact-prod-m101/Store/env_account | base64
+      env:
+        ENV64_FILES: ${{ steps.fetch-env.outputs.stdout }}
+
+      # Step 3: Verify and store the fetched data into an environment variable
+    - name: Set environment variable for fetched data
+      if: success()
+      run: |
+        if [ -z "${{ steps.fetch-env.outputs.stdout }}" ]; then
+          echo "Error: ENV64_FILES is empty!"
+          exit 1
+        fi
+        echo "ENV64_FILES=${{ steps.fetch-env.outputs.stdout }}" >> $GITHUB_ENV
+
+      # Step 4: Decode the file and create .env
+    - name: Decode and create .env file
+      run: |
+        echo "${{ env.ENV64_FILES }}" | base64 --decode > .env
+        echo "Decoded .env content:"
+        cat .env
 
     - name: Verify .env file
       run: |
