Update env-cicd.yml

diff --git a/.github/workflows/env-cicd.yml b/.github/workflows/env-cicd.yml
--- a/.github/workflows/env-cicd.yml
+++ b/.github/workflows/env-cicd.yml
@@ -38,16 +38,27 @@ jobs:
         port: ${{ secrets.PRODSM101_PORT_SSH }}
         script: |
           cat /opt/artitact-prod-m101/Store/.env_account | base64
-          
-      # Save the Base64 output as an environment variable
+      # Output stdout as a custom output variable
       continue-on-error: false  # Ensure this step fails if the SSH command fails
-      env:
-        ENV64_FILES: ${{ steps.fetch-env.outputs.stdout }}
+
+    - name: Debug fetch-env output
+      run: |
+        echo "Output from fetch-env:"
+        echo "${{ steps.fetch-env.outputs.stdout }}"
+        if [ -z "${{ steps.fetch-env.outputs.stdout }}" ]; then
+          echo "Error: Output from fetch-env is empty."
+          exit 1
+        fi
+
+    - name: Set environment variable for fetched base64 data
+      run: |
+        echo "ENV64_FILES=${{ steps.fetch-env.outputs.stdout }}" >> $GITHUB_ENV
 
     - name: Decode Base64 environment file
       run: |
         echo "$ENV64_FILES" | base64 --decode > .env
         cat .env  # Optional: Check the content of the .env file for debugging
+
         
     - name: Copy .env to .env.local
       run: cp .env .env.local
